### ISSUE TITLE
webpack_asset_path is not defined

### ISSUE THREAD

**Issue by kikoanis** [catamphetamine/webpack-isomorphic-tools#147]
I am getting ```webpack_asset_path is not defined``` after upgrading to 3.0.4. I tracked it down to [this line](https://github.com/catamphetamine/webpack-isomorphic-tools/blob/c9580a78c3a4bff439b4e78b94db4df40e0e0961/source/index.js#L608)

I wonder if you meant the parameter ```asset_path``` and was mistyped.

**Comment by catamphetamine** [comment]
Oh.
Yeah, I released `3.0.4` today with an updated `package.json` info but didn't check for previously unreleased commits.
Seems that there was one:
https://github.com/catamphetamine/webpack-isomorphic-tools/commit/feb0bf1057242722c30e3f109658c866d6d76985
And it introduced the changes which now result in an exception thrown.

**Comment by catamphetamine** [comment]
Yeah, you were right.
Good catch, thx.
I remember you btw, you were around before this repo got many stars.
Fixed now.

**Comment by kikoanis** [comment]
Thanks for the quick fix. Yes, I have been a long time user of your fantastic project and it's been so helpful to me.
