### ISSUE TITLE
Ability to specify publicPath at runtime for server-side?

### ISSUE THREAD

**Issue by biddlem** [catamphetamine/webpack-isomorphic-tools#150]
Q: Is it possible to specify the publicPath at runtime when handling server-side requests?

I am able to achieve it by specifying "__webpack_public_path__" in my application's entry point file, but that only works on for the client-side requests.

**Comment by catamphetamine** [comment]
Why aren't you using Webpack's `output.publicPath`, it works on both client and servere.
