### ISSUE TITLE
Inside CSS, background-url is packaged into absolute paths

### ISSUE THREAD

**Issue by ysk2014** [catamphetamine/webpack-isomorphic-tools#151]
`background: #ababab url('../../../resources/images/star_bg.jpg') no-repeat center center；`
package to
`background: #ababab url(D:\workspace\react-mobile-boilerplate\public\images/star_bg.jpg) no-repeat center center;`

**Comment by catamphetamine** [comment]
Filesystem `url()` is a bug in your configuration.
Use relative URLs instead in `output.publicPath`.
