### ISSUE TITLE
Resolving webpack custom module paths

### ISSUE THREAD

**Issue by Mike-Now** [catamphetamine/webpack-isomorphic-tools#153]
Just wanted to share my solution to the problem I encountered with additional module paths
in my webpack config. 
Imports like:
`
import MyComponent from 'src/components/MyComponent'; 
`
are resolved by webpack using the [resolve.modules](https://webpack.js.org/configuration/resolve/#resolve-modules) option.

_webpack-isomorphic-tools_ cannot resolve those paths by its own. To enable 
custom modules resolution simply set up [babel-plugin-module-resolver](https://github.com/tleunen/babel-plugin-module-resolver) exactly as in Readme.

**Comment by catamphetamine** [comment]
Oh, resolving via Babel is really the right way to go.
I see more and more older hacks being removed via babel plugins.
Elegant enough.
