### ISSUE TITLE
Clarification in README

### ISSUE THREAD

**Issue by sunglux** [catamphetamine/webpack-isomorphic-tools#157]
In README,

> An alternative solution exists now: to compile server-side code with Webpack the same way it already compiles the client-side code. This is the officially recommended way to go ...

Could you provide a link to the official recommendation? It would help readers if the README linked to the source.

**Comment by catamphetamine** [comment]
Well, I guess it would be `target: node` docs:
https://webpack.js.org/configuration/target/#target

**Comment by catamphetamine** [comment]
I updated the readme.
