### ISSUE TITLE
Babel 7 is not supported

### ISSUE THREAD

**Issue by idangozlan** [catamphetamine/webpack-isomorphic-tools#162]
Babel 7 is not supported, getting the following error while trying to use it:
Error: Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version of @babel/core,

**Comment by catamphetamine** [comment]
Yeah, I guess it won't be, because this project is no longer supported.

**Comment by idangozlan** [comment]
Do you have any recommendation for alternatives? thanks!

**Comment by catamphetamine** [comment]
Well, there's `universal-webpack` if you haven't already looked at it.
Then it's Next.js, which is very popular (seems to be).
In any case, it would be a big refactoring for an app, so you might as well re-think the architecture if Babel 7 is really required in your case.

**Comment by idangozlan** [comment]
got it. thanks!
