### ISSUE TITLE
(/config/webpack-assets.json not found)

### ISSUE THREAD

**Issue by binyellow** [catamphetamine/webpack-isomorphic-tools#163]
Hello, I checked my webpack configuration, context and basePath, still can't solve the problem, can you help me see it?

Problem screenshot
![image](https://user-images.githubusercontent.com/29519985/56093501-2d857000-5efc-11e9-9a43-ac2c380917a7.png)

this is my [projectPath](https://github.com/binyellow/react-ssr/tree/webpack-isomorphic-tools)

**Comment by catamphetamine** [comment]
Hi.

> can you help me see it?

No, because I'm no longer supporting this library, so you're on your own here.
I'm closing this issue because it's not a bug report, and even if it was a bug report it wouldn't be fixed because it's no longer supported.
I wrote this comment so that you don't wait for me to respond.
